apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pramod-pvc17
  namespace: ns17
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: fast-17
