apiVersion: v1
kind: Service
metadata:
  name: py-service-17
  namespace: ns17
spec:
  type: NodePort
  selector:
    app: python-app-17
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30117